version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 30
    directory: "/"
    schedule:
      interval: "weekly"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

    groups:
      prettier:
        patterns:
          - prettier*
      eslint:
        patterns:
          - eslint*
          - "@typescript-eslint*"
      commitlint:
        patterns:
          - commitlint*
      storybook:
        patterns:
          - storybook
          - "@storybook*"
      test:
        patterns:
          - jest*
          - "@testing-library*"
      astro:
        patterns:
          - astro
          - "@astro*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      radix:
        patterns:
          - "@radix-ui*"
      tsconfig:
        patterns:
          - "@tsconfig*"
