version: "3"

dotenv:
  - .env
  - .env.local

tasks:
  init:
    cmds:
      - bash ./init.bash
  cloudflare-init:
    cmds:
      - pnpm install
      - cmd: pnpm --filter infra init
        ignore_error: true
      - pnpm --filter plan
      - pnpm --filter apply
      - pnpm --filter show
      - pnpm wrangler pages deploy app/keyword-game/dist --project-name keyword-game
      - pnpm wrangler pages deploy app/www/dist --project-name www
