version: "3"

dotenv:
  - .env
  - .env.local

tasks:
  www-init:
    - task: www-prepare
    - task: www-create-projects
    - task: www-deploy-projects

  www-prepare:
    cmds:
      - pnpm install

  www-create-projects:
    cmds:
      - cmd: pnpm wrangler pages project create --project-name www-public --production-branch main
        ignore_error: true
      - cmd: pnpm wrangler pages project create --project-name www-preview --production-branch main
        ignore_error: true

  www-deploy-projects:
    cmds:
      - pnpm build --filter www-public
      - cmd: pnpm wrangler pages deploy packages/www-public/dist --project-name www-public
        ignore_error: true
      - pnpm build --filter www-preview
      - cmd: pnpm wrangler pages deploy packages/www-preview/dist --project-name www-preview
        ignore_error: true

