version: '3'

tasks:
  generate-dotenv-example:
    cmds:
      - bat .env.local | sd '(=)(.+?)(\s#\s.+)?$' '$1$3' > .env.local.example
  deploy-init:
    cmds:
      - pnpm install
      - pnpm build
      - source .env.local
      - pnpm wrangler pages deploy packages/www-prod/dist --project-name www-prod
      - pnpm wrangler pages deploy packages/www-preview/dist --project-name www-preview
