version: "3"

dotenv:
  - .env
  - .env.local

tasks:
  generate-dotenv-example:
    cmds:
      - bat .env.local | sd '(=)(.+?)(\s#\s.+)?$' '$1$3' > .env.local.example

  init:
    - task: prepare
    - task: create-projects
    - task: deploy-projects

  prepare:
    cmds:
      - pnpm install

  create-projects:
    cmds:
      - cmd: pnpm wrangler pages project create --project-name www-public --production-branch main
        ignore_error: true
      - cmd: pnpm wrangler pages project create --project-name www-preview --production-branch main
        ignore_error: true

  deploy-projects:
    cmds:
      - pnpm build
      - pnpm wrangler pages deploy packages/www-public/dist --project-name www-prod
      - pnpm wrangler pages deploy packages/www-preview/dist --project-name www-preview
