name: checkout
description: actions/checkout wrapper
inputs:
  fetch-depth:
    required: false

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
