name: publish-cloudflare-pages
description: publish cloudflare pages
inputs:
  gitHubToken:
    required: true
  accountId:
    required: true
  apiToken:
    required: true
  project-name:
    required: true
  dist:
    required: true
  build:
    default: pnpm build
    required: false

runs:
  using: composite
  steps:
    - name: init
      uses: ./.github/actions/init

    - name: setup pnpm
      uses: ./.github/actions/setup-pnpm

    - name: build www
      shell: bash
      run: ${{ inputs.build }}

    - name: publish www
      uses: cloudflare/pages-action@v1
      with:
        workingDirectory: .
        directory: ${{ inputs.dist }}
        projectName: ${{ inputs.project-name }}
        wranglerVersion: "3"
        branch: ${{ github.ref }}
        gitHubToken: ${{ inputs.gitHubToken }}
        accountId: ${{ inputs.accountId }}
        apiToken: ${{ inputs.apiToken }}
