on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  publish-www-public-production:
    if: github.ref_name == 'main'
    name: publish www-public production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    environment:
      name: "www production"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-public
          dist: ./packages/www-prod
          build: pnpm build --filter www-prod
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PUBLIC }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PUBLIC }}
    
  publish-www-preview-production:
    if: github.ref_name == 'main'
    name: publish www-preview production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    environment:
      name: "www production"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-preview
          dist: ./packages/www-preview
          build: pnpm build --filter www-preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PREVIEW }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PREVIEW }}

  publish-www-public-staging:
    if: github.ref_name != 'main'
    name: publish www-public staging
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    environment:
      name: "www staging"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-public
          dist: ./packages/www-prod
          build: pnpm build --filter www-prod
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PUBLIC }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PUBLIC }}
    
  publish-www-preview-staging:
    if: github.ref_name != 'main'
    name: publish www-preview staging
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    environment:
      name: "www staging"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-preview
          dist: ./packages/www-preview
          build: pnpm build --filter www-preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PREVIEW }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PREVIEW }}