on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  publish-www-public-production:
    if: github.ref_name == 'main'
    name: publish www-public production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-public
          dist: ./packages/www-prod
          build: pnpm build --filter www-prod
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    
  publish-www-preview-production:
    if: github.ref_name == 'main'
    name: publish www-preview production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-preview
          dist: ./packages/www-preview
          build: pnpm build --filter www-preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  publish-www-public-test:
    if: github.ref_name != 'main'
    name: publish www-public test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-public
          dist: ./packages/www-prod
          build: pnpm build --filter www-prod
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
  publish-www-preview-test:
    if: github.ref_name != 'main'
    name: publish www-preview test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: publish-pages
        uses: ./.github/actions/publish-pages
        with:
          project-name: www-preview
          dist: ./packages/www-preview
          build: pnpm build --filter www-preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}