on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  static-analysis:
    name: static analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: setup pnpm
        uses: ./.github/actions/setup-pnpm  
      - name: static-analysis
        run: pnpm format
