name: static-analysis
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  static-analysis:
    name: static analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: init
        uses: ./.github/actions/init
      - name: setup turborepo
        uses: ./.github/actions/setup-turborepo
      - name: setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: static-analysis
        run: pnpm all:check
